name: Pipeline CI/CD sonarqube-code-quality-scan-job

on:
  pull_request:
    branches:
      - main

jobs:

  sonarqube-code-quality-scan-job:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # v8.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

  trivy-image-security-scan-job:
      runs-on: ubuntu-latest
      steps:      

        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Download and install Trivy
          run: |
            sudo apt-get update && sudo apt-get install -y curl
            curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.74.0/trivy_0.74.0_Linux-32bit.tar.gz -o trivy.tar.gz
            tar xzvf trivy.tar.gz
            sudo mv trivy /usr/local/bin/
            trivy --version


  # docker build -t ${{ env.IMAGE_NAME }} .
  # trivy image ${{ env.IMAGE_NAME }}
  # trivy fs .  # solution alternative 
        - name: Run Trivy Docker image vulnerability scan
          run: |
            IMAGE_NAME="frontend-app:latest"
            docker build -t $IMAGE_NAME .
            trivy image $IMAGE_NAME
            



